ALTER TABLE conversations ADD COLUMN IF NOT EXISTS unit VARCHAR(255) NULL AFTER subject;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS substatus VARCHAR(100) NULL AFTER status;
CREATE TABLE IF NOT EXISTS conversation_substatuses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    color VARCHAR(7) NULL DEFAULT '#6c757d',
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
